// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Baker struct {
	ID        int32
	Img       sql.NullString
	Name      sql.NullString
	Address   sql.NullString
	Suburb    sql.NullString
	Postcode  sql.NullString
	Contact   sql.NullString
	Specialty sql.NullString
	Creator   sql.NullString
}

type Review struct {
	ID       int32
	BakerID  sql.NullString
	Review   sql.NullString
	Rating   sql.NullString
	UserName sql.NullString
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	UserName       string
	UserType       string
	Email          string
	PasswordDigest string
}
