// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Baker struct {
	ID        uuid.UUID
	Img       string
	Name      string
	Address   string
	Suburb    string
	Postcode  string
	Contact   string
	Specialty string
	Creator   uuid.UUID
}

type Review struct {
	ID        uuid.UUID
	BakerID   uuid.UUID
	Review    string
	Rating    string
	UserID    uuid.UUID
	CreatedAt time.Time
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	UserName       string
	UserType       string
	Email          string
	PasswordDigest string
}
