// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Baker struct {
	ID        uuid.UUID
	Img       sql.NullString
	Name      string
	Address   sql.NullString
	Suburb    sql.NullString
	Postcode  sql.NullString
	Contact   sql.NullString
	Specialty sql.NullString
	Creator   uuid.UUID
}

type Review struct {
	ID      uuid.UUID
	BakerID uuid.UUID
	Review  sql.NullString
	Rating  sql.NullString
	UserID  uuid.UUID
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	UserName       string
	UserType       string
	Email          string
	PasswordDigest string
}
